<?php

return [
    'client'   => [
        'User-Agent'  => 'Huth Service API',
        'headers'     => [], # Not Authorization & User-Agent
        'form_params' => [], # Not case & argument
        'route'       => '/api/huth-api/{client}',
    ],
    'config' => [
        'templates' => [
            'cache:stores:redis' => [
                'driver'          => 'redis',
                'connection'      => 'cache',
                'lock_connection' => 'default',
            ],
            'cache:stores:dynamodb' => [
                'driver'   => 'dynamodb',
                'key'      => null,
                'secret'   => null,
                'region'   => null,
                'table'    => 'cache',
                'endpoint' => null,
            ],
            'database:connections:sqlite' => [
                'driver'                  => 'sqlite',
                'url'                     => '',
                'database'                => '',
                'prefix'                  => '',
                'foreign_key_constraints' => true,
            ],
            'database:connections:mysql' => [
                'driver'         => 'mysql',
                'url'            => null,
                'host'           => 'localhost',
                'port'           => '3306',
                'database'       => 'forge',
                'username'       => null,
                'password'       => null,
                'unix_socket'    => '',
                'charset'        => 'utf8mb4',
                'collation'      => 'utf8mb4_unicode_ci',
                'prefix'         => '',
                'prefix_indexes' => true,
                'strict'         => true,
                'engine'         => null,
            ],
            'database:connections:pgsql' => [
                'driver'         => 'pgsql',
                'url'            => null,
                'host'           => '127.0.0.1',
                'port'           => '5432',
                'database'       => 'forge',
                'username'       => null,
                'password'       => null,
                'charset'        => 'utf8',
                'prefix'         => '',
                'prefix_indexes' => true,
                'schema'         => 'public',
                'sslmode'        => 'prefer',
            ],
            'database:connections:redis.default' => [
                'url'      => '',
                'host'     => '127.0.0.1',
                'password' => null,
                'port'     => '6379',
                'database' => '0',
            ],
            'database:connections:redis.cache' => [
                'url'      => null,
                'host'     => '127.0.0.1',
                'password' => null,
                'port'     => '6379',
                'database' => '1',
            ],
            'filesystems:disks:ftp' => [
                'driver'   => 'ftp',
                'host'     => null,
                'username' => null,
                'password' => null,
            ],
            'filesystems:disks:s3' => [
                'driver'                  => 's3',
                'key'                     => null,
                'secret'                  => null,
                'region'                  => null,
                'bucket'                  => null,
                'url'                     => null,
                'endpoint'                => null,
                'use_path_style_endpoint' => false,
            ],
            'mail:mailers:smtp' => [
                'transport'  => 'smtp',
                'host'       => 'smtp.mailgun.org',
                'port'       => 587,
                'encryption' => 'tls',
                'username'   => null,
                'password'   => null,
                'timeout'    => null,
                'auth_mode'  => null,
            ],
            'mail:mailers:from' => [
                'address' => 'no-reply@huth.it',
                'name'    => 'Norman Huth',
            ],
            'queue:connections:database' => [
                'driver'       => 'database',
                'table'        => 'jobs',
                'queue'        => 'default',
                'retry_after'  => 90,
                'after_commit' => false,
            ],
            'queue:connections:redis' => [
                'driver'       => 'redis',
                'connection'   => 'default',
                'queue'        => 'default',
                'retry_after'  => 90,
                'block_for'    => null,
                'after_commit' => false,
            ],
            'services:general' => [
                'client_id'     => null,
                'client_secret' => null,
                'redirect'      => null,
            ],
            'services:telegram' => [
                'bot'           => '',
                'client_id'     => null,
                'client_secret' => '',
                'redirect'      => '',
            ],
            'services:telegram-bot-api' => [
                'token'    => null,
                'receiver' => null,
                'group_id' => null,
            ],
            'services:youtube' => [
                'client_secret' => '',
                'redirect'      => '',
                'channel_id'    => null,
                'api_key'       => null,
            ],
            'services:discord' => [
                'client_id'                => '',
                'client_secret'            => '',
                'redirect'                 => '',
                'allow_gif_avatars'        => true,
                'avatar_default_extension' => 'jpg',
            ],
        ],
    ],
];
